TISSUES=["ADIPOSE_TISSUE","ADRENAL_GLAND","ARTERIAL_BLOOD_VESSEL","BLOOD",
				 "BLOOD_VESSEL","BONE_ELEMENT","BONE_MARROW","BRAIN",
				 "BREAST","COLON","CONNECTIVE_TISSUE","EAR",
				 "EMBRYO","ENDOCRINE_GLAND","EPITHELIUM","ESOPHAGUS",
				 "EXOCRINE_GLAND","EXTRAEMBRYONIC_COMPONENT","EYE","GONAD","GENERIC",
				 "HEART","IMMUNE_ORGAN","INTESTINE","KIDNEY",
				 "LARGE_INTESTINE","LIMB","LIVER","LUNG",
				 "LYMPH_NODE","LYMPHOID_TISSUE","MAMMARY_GLAND","MOUTH",
				 "MUSCULATURE_OF_BODY","NERVE","OVARY","PANCREAS",
				 "PENIS","PLACENTA","PROSTATE_GLAND","SKIN_OF_BODY",
				 "SKIN_OF_PREPUCE_OF_PENIS","SMALL_INTESTINE","SPINAL_CORD","SPLEEN",
				 "STOMACH","TESTIS","THYMUS","THYROID_GLAND",
				 "UTERUS","VAGINA","VASCULATURE"]

CHROMS=[x for x in range(1,23)]

rule all:
	input:
		expand("/nfs/turbo/boylelab/crone/data/1KG/RegDB_custom_baselineLD_v1.2/test/customized_baselineLD_cts.RegDB.{tissue}.{chrom}.out",tissue=TISSUES,chrom=CHROMS)
rule calculate_LDscores:
	resources:
		time      = "5:00:00",
		mem_mb    = "65000",
		account   = "apboyle99",
		partition = "largemem,standard"
	input:
		script = "/nfs/turbo/boylelab/crone/tools/ldsc/ldsc.py",
		bfile  = "/nfs/turbo/boylelab/crone/data/1KG/1000G_EUR_Phase3_plink/1000G.EUR.QC.RegDB.{wildcard.chrom}",
		annot  = "/nfs/turbo/boylelab/crone/data/1KG/RegDB_custom_baselineLD_v1.2/serial/customized_baselineLD_cts.RegDB.{wildcard.tissue}.{wildcard.chrom}.annot.gz",
		hm3    = "/nfs/turbo/boylelab/crone/data/1KG/hapmap3_snps/hm.{wildcard.chrom}.snp",
	output:
		prefix = "/nfs/turbo/boylelab/crone/data/1KG/RegDB_custom_baselineLD_v1.2/test/customized_baselineLD_cts.RegDB.{wildcard.tissue}.{wildcard.chrom}"
	shell:
		"python {input.script} --l2 --bfile {input.bfile} --ld-wind-cm 1 --out {output.prefix} --annot {input.annot} --print-snps {input.hm3} > {output.prefix}.out"