configfile: "config.yaml"

TRAITS=["BMI","height","HDL","LDL"]

TISSUES=["ADIPOSE_TISSUE","ADRENAL_GLAND","ARTERIAL_BLOOD_VESSEL","BLOOD",
				 "BLOOD_VESSEL","BONE_ELEMENT","BONE_MARROW","BRAIN",
				 "BREAST","COLON","CONNECTIVE_TISSUE","EAR",
				 "EMBRYO","ENDOCRINE_GLAND","EPITHELIUM","ESOPHAGUS",
				 "EXOCRINE_GLAND","EXTRAEMBRYONIC_COMPONENT","EYE","GONAD","GENERIC",
				 "HEART","IMMUNE_ORGAN","INTESTINE","KIDNEY",
				 "LARGE_INTESTINE","LIMB","LIVER","LUNG",
				 "LYMPH_NODE","LYMPHOID_TISSUE","MAMMARY_GLAND","MOUTH",
				 "MUSCULATURE_OF_BODY","NERVE","OVARY","PANCREAS",
				 "PENIS","PLACENTA","PROSTATE_GLAND","SKIN_OF_BODY",
				 "SKIN_OF_PREPUCE_OF_PENIS","SMALL_INTESTINE","SPINAL_CORD","SPLEEN",
				 "STOMACH","TESTIS","THYMUS","THYROID_GLAND",
				 "UTERUS","VAGINA","VASCULATURE"]

CHROMS=[x for x in range(1,23)]

LDSC_PATH  = config["ldsc"]["path"]
LDSC_CONDA = config["ldsc"]["conda"]
LDSC_PYTHON = config["ldsc"]["python"]

rule all:
	input:
		expand(config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.{chrom}.l2.ldscore.gz",tissue=TISSUES,chrom=CHROMS)
		expand(config["ldsc"]["h2_path"] + "{trait}/{trait}/{trait}.{tissue}.results",trait=TRAITS,tissue=TISSUES)

rule calculate_LDscores:
	conda: LDSC_CONDA
	input:
		script = LDSC_PATH,
		python = LDSC_PYTHON,
		annot  = config["ldsc"]["baselineLD"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.{chrom}.annot.gz",
		hm3    = config["ldsc"]["HM3"] + "hm.{chrom}.snp"
	output:
		#expand(config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.{chrom}.{ext}",tissue=TISSUES,chrom=CHROMS,ext=["log","l2.ldscore.gz","l2.M","l2.M_5_50","OK"]),
		config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.{chrom}.l2.ldscore.gz",
		config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.{chrom}.OK"
	params:
		bfile = config["ldsc"]["1KG"] + "1000G.EUR.QC.RegDB",
		ld_wind_cm = 1,
		out = config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized"
	shell:
		"{input.python} {input.script}"
		" --l2"
		" --bfile  {params.bfile}.{wildcards.chrom}"
		" --ld-wind-cm {params.ld_wind_cm}"
		" --out {params.out}.{wildcards.tissue}.{wildcards.chrom}"
		" --annot {input.annot}"
		" --print-snps {input.hm3} && touch {params.out}.{wildcards.tissue}.{wildcards.chrom}.OK"

rule calculate_h2:
	conda: LDSC_CONDA
	input:
		script = LDSC_PATH,
		python = LDSC_PYTHON,
		sumstats = config["ldsc"]["GWAS"] + "{trait}/LDSC/{trait}.sumstats.gz",
		ref_ld_chr = expand(config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{{tissue}}.{chrom}.l2.ldscore.gz",chrom=CHROMS)
	output:
		config["ldsc"]["h2_path"] + "{trait}/{trait}.{tissue}.results"
	params:
		script = LDSC_PATH,
		python = LDSC_PYTHON,
		out = config["ldsc"]["h2_path"] + "{trait}/{trait}/{trait}.{tissue}",
		done = config["ldsc"]["h2_path"] + "{trait}/{trait}/{trait}.{tissue}.OK",
		sumstats = config["ldsc"]["GWAS"] + "{trait}/LDSC/{trait}.sumstats.gz",
		ldscore = config["ldsc"]["ldscore_path"] + "customized_baselineLD_cts.RegDB.quantile_normalized.{tissue}.",
		weights = config["ldsc"]["weights"],
		freq = config["ldsc"]["freq"]
	shell:
		"{input.python} {input.script}"
		" --h2 {input.sumstats}"
		" --ref-ld-chr {input.ref_ld_chr}"
		" --w-ld-chr {params.weights}"
		" --overlap-annot"
		" --frqfile-chr {params.freq}"
		" --out {params.out}/{wildcards.trait}/{wildcards.trait}.{wildcards.tissue}"
		" --print-coefficients --print-delete-vals && touch {params.done}/{wildcards.trait}/{wildcards.trait}.OK"